### ISSUE TITLE
 MacOSX show a error info

### ISSUE THREAD

**Issue by ver007** [jakub-olczyk/miniVim#4]
MacOSX Log:
60:Traceback (most recent call last):
  File "/miniVim/src/Utils.py", line 39, in excepted_wrapper
    func(*args, **kwargs)
  File "/miniVim/src/Dispatcher.py", line 51, in execute
    cmd = self.commands[cmd_letter]
KeyError: 'KEY_DOWN'

61:Traceback (most recent call last):
  File "/miniVim/src/Utils.py", line 39, in excepted_wrapper
    func(*args, **kwargs)
  File "/miniVim/src/Dispatcher.py", line 51, in execute
    cmd = self.commands[cmd_letter]
KeyError: 'KEY_UP'

**Comment by jakub-olczyk** [comment]
Thanks for feedback! Actually this are the debug logs that might be used for adding functionality to this very basic (and veeery unpolished) vi clone. If you dig into the code you'll see that all of the keys that don't have any function mapped (as with the arrow keys) are ignored (using the `excepted` decorator) (although you can see that they were pressed at the bottom of the editing screen).

As such this is not really an error per se. Nonetheless thanks for checking out the code :)
